make assm:
	sudo g++ -s -o chat_server.s   SaveRestor.cpp User.cpp Message.cpp Chat.cpp  Chats.cpp TCP_server.cpp Main.cpp
compile server: 
	sudo g++ -o chat_server   SaveRestor.cpp User.cpp Message.cpp Chat.cpp  Chats.cpp TCP_server.cpp Main.cpp

	