
compile server: 
	sudo g++ -std=c++20 -D_DEBUG -o chat_server   SaveRestor.cpp User.cpp Message.cpp Chat.cpp  Chats.cpp TCP_server.cpp Server.cpp DB_Queries_DDL.cpp DB_Queries_DML.cpp Main.cpp `mysql_config --cflags --libs`

